import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='h-screen w-full flex flex-col items-center justify-center gap-8'>
        <h1 className='font-bold uppercase text-xl hover:text-red-800 hover:text-7xl'>Hi there!</h1>
        <Image className='' src='/laptop-image.jpg' alt='lap' height={300} width={300}/>
      </div>
      
    </>
  )
}
